services:


  db-test:
    container_name: demo-spring-boot
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: demo
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: test
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge